export { checkHandler } from "./testHandler.js";
export { signup, login, verifyEmail, forgotPassword, verifyResetOTP, resetPassword, resendVerification, googleAuthCallback } from "./authHandler.js";
export { getProfile, updateProfile, uploadProfilePicture } from "./studentHandler.js";
export { createCourse, getAllCourses, getMyCourses, updateCourse, deleteCourse, publishCourse } from "./courseHandler.js";
export { createInstructor, getAllInstructors, getInstructorById, removeInstructor, createStudent, getAllStudents, getStudentById, removeStudent, getAdminDashboardStats } from "./adminHandler.js";
export { getDashboardStats, getCourseDetails } from "./instructorHandler.js";
export { createSection } from "./sectionHandler.js";
export { uploadThumbnail, createUnifiedLesson, deleteLesson } from "./lessonHandler.js";
export { enrollStudent, watchLesson, updateProgress } from "./enrollmentHandler.js";
export { submitAssignment, getInstructorInbox, reviewSubmission, getStudentInbox, deleteSubmission } from "./assignmentHandler.js";
export { markAsRead, getUnreadCount } from "./notificationHandler.js";